### ISSUE TITLE
fnLocation passed into spvm_state_prepare is not valid.

### ISSUE THREAD

**Issue by Danielmelody** [dfranx/SPIRV-VM#1]
Both in README.md and example.c, I found this code strange:
```c
    spvm_source fnMain = spvm_state_get_result(state, "main");
    spvm_state_prepare(state, fnMain);
```
where fnMain is a pointer, but `spvm_state_prepare` declares as 
```c
void spvm_state_prepare(spvm_state_t state, spvm_word fnLocation)
{
	state->code_current = state->results[fnLocation].source_location;
	state->current_function = &state->results[fnLocation];
```

which makes `state->results[fnLocation]` accessed an invalid memory.

If I change the call to
```c
spvm_state_prepare(state, *fnMain);
```

I got
```bash
0.00 0.00 0.00 0.00
discarded: 0
```

However from the source examples/shader.glsl, this is incorrect.

What did I do wrong? or  there is a bug here?

**Comment by dfranx** [comment]
I've changed how `spvm_state_prepare` works and forgot to update README and `example.c`...
It should now be:
```c
spvm_word fnMain = spvm_state_get_result_location(state, "main");
spvm_state_prepare(state, fnMain);
```

**Comment by Danielmelody** [comment]
BTW, any plans for unit tests?

I 'm interesting on using your project, but I 'm not sure it is still in an early stage or full featured.

**Comment by Danielmelody** [comment]
Well, I 'm developing a SDL targeting SPIR-V, and I 'm interesting debugging and validating my compiler by this vm. 
I 've googled an found this is the only SPIR-V vm in the world. I 'd be very appreciate if you can make this project more serious, like, for example, well tested.
